import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function HouseModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/house/house.gltf");
  return (
    <group ref={group} {...props} dispose={null} scale={0.5}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={
            materials.ardoise_001_ovcolacacaccolpic12contpic02_Room_Entity_Material
          }
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.bamboo___bamboo_feuille}
          material-color={"red"}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.bar_004___lambert10sg}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.beige_006_Wall_Entity_Material}
          material-color={"green"}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.blanc_001_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.blanc_001_Wall_Entity_Material}
          material-color={"brown"}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.bois_080}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.bois_102}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.bois_cloture_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={
            materials.brique_007_ovcolacacaccolpic12contpic02_Wall_Entity_Material
          }
          material-color={"brown"}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.brique_008_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.brique_015_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.buisson___buisson_branche_texture}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.canape_012___mat_bois089sg}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.canape_012___mat_tissus057_2sg}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.canape_012___mat_tissus095_bissg}
          material-color={"brown"}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.car_madeon_000___brakedisc}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.car_madeon_000___madeon_nypd_tex}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.car_madeon_000___tire}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.car_stalion_000___textures}
          material-color={"brown"}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.carreaux_anciens_002_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.carrelage_007_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.carrelage_013_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={
            materials.carrelage_046_ovcolbfbfbfcolpic12contpic03_Room_Entity_Material
          }
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.chaise_025___mat_tissus033sg}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.d37b3d6f37d136f639429727939b5de2}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={
            materials.d37b3d6f37d136f639429727939b5de2_ovcol4c4c4ccolpic12contpic09_Wall_Entity_Material
          }
          material-color={"orange"}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.enduit_004_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.enduit_004_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials.etagere_murale_004____mat_livrecouverture1sg}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials.etagere_murale_004____mat_orsombresg}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials.etagere_murale_004___mat_boissg}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.fake_mat_123_171_51_255}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.fake_mat_132_48_42_255}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.fake_mat_132_48_42_255}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.fake_mat_135_142_145_255}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.fake_mat_135_142_145_255}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials.fake_mat_13_11_11_255}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.fake_mat_13_11_11_255}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.fake_mat_182_163_144_255}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.fake_mat_182_163_144_255}
        />
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials.fake_mat_194_201_203_255}
        />
        <mesh
          geometry={nodes.Object_44.geometry}
          material={materials.fake_mat_194_201_203_255}
        />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.fake_mat_197_155_76_255}
        />
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.fake_mat_197_155_76_255}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.fake_mat_203_18_13_255}
        />
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials.fake_mat_21_43_168_255}
        />
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials.fake_mat_233_222_188_255}
        />
        <mesh
          geometry={nodes.Object_50.geometry}
          material={materials.fake_mat_233_222_188_255}
        />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.fake_mat_235_206_152_255}
        />
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials.fake_mat_235_206_152_255}
        />
        <mesh
          geometry={nodes.Object_53.geometry}
          material={materials.fake_mat_235_236_234_255}
        />
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials.fake_mat_235_236_234_255}
        />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.fake_mat_255_255_255_32}
        />
        <mesh
          geometry={nodes.Object_56.geometry}
          material={materials.fake_mat_57_48_42_255}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.fake_mat_57_48_42_255}
        />
        <mesh
          geometry={nodes.Object_58.geometry}
          material={materials.fake_mat_76_108_52_255}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.fake_mat_76_108_52_255}
        />
        <mesh
          geometry={nodes.Object_60.geometry}
          material={materials.fake_mat_82_64_86_255}
        />
        <mesh
          geometry={nodes.Object_61.geometry}
          material={materials.fake_mat_82_64_86_255}
        />
        <mesh
          geometry={nodes.Object_62.geometry}
          material={materials.fake_mat_91_91_90_255}
        />
        <mesh
          geometry={nodes.Object_63.geometry}
          material={materials.fake_mat_91_91_90_255}
        />
        <mesh
          geometry={nodes.Object_64.geometry}
          material={
            materials.fauteuil_piano_chrome___fauteuil_piano_chrome_canape1
          }
        />
        <mesh
          geometry={nodes.Object_65.geometry}
          material={materials.frene____frenefeuilles1}
        />
        <mesh
          geometry={nodes.Object_66.geometry}
          material={materials.ground_herbe_1_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.ground_herbe_2_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_68.geometry}
          material={
            materials.kitchen_classic_style_base_cabinet_008___lambert2sg
          }
          material-color={"brown"}
        />
        <mesh
          geometry={nodes.Object_69.geometry}
          material={materials.kitchen_classic_style_dishwasher_000___phong9sg}
        />
        <mesh
          geometry={nodes.Object_70.geometry}
          material={materials.kitchen_classic_style_double_oven_000___phong4sg}
        />
        <mesh
          geometry={nodes.Object_71.geometry}
          material={materials.lambris_ext_003_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_72.geometry}
          material={materials.marbre_006}
        />
        <mesh
          geometry={nodes.Object_73.geometry}
          material={materials.metal_014}
        />
        <mesh
          geometry={nodes.Object_74.geometry}
          material={materials.metal_014_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_75.geometry}
          material={materials.metal_014_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_76.geometry}
          material={materials.meuble_off_012___boisclair1}
        />
        <mesh
          geometry={nodes.Object_77.geometry}
          material={materials.meuble_off_012___wood_structure1}
        />
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials.meuble_scandinave_ww___phong95}
        />
        <mesh
          geometry={nodes.Object_79.geometry}
          material={materials.mur_vegetal_off___phong150}
        />
        <mesh
          geometry={nodes.Object_80.geometry}
          material={materials.mur_vegetal_off___phong151}
        />
        <mesh
          geometry={nodes.Object_81.geometry}
          material={materials.mur_vegetal_off___phong31}
        />
        <mesh
          geometry={nodes.Object_82.geometry}
          material={materials.pack_003_salon_cheminee___material__116}
        />
        <mesh
          geometry={nodes.Object_83.geometry}
          material={materials.pack_003_salon_cheminee___material__119}
        />
        <mesh
          geometry={nodes.Object_84.geometry}
          material={materials.pack_003_salon_cheminee___material__120}
        />
        <mesh
          geometry={nodes.Object_85.geometry}
          material={materials.pack_003_salon_television___material__80_1}
        />
        <mesh
          geometry={nodes.Object_86.geometry}
          material={materials.pack_003_salon_television___material__81}
        />
        <mesh
          geometry={nodes.Object_87.geometry}
          material={materials.pack_005_bureau_002_plante___nopaint_feuilles}
        />
        <mesh
          geometry={nodes.Object_88.geometry}
          material={materials.pack_005_bureau_002_plante___pot}
        />
        <mesh
          geometry={nodes.Object_89.geometry}
          material={materials.pack_005_bureau_002_plante___terreau}
        />
        <mesh
          geometry={nodes.Object_90.geometry}
          material={materials.papier_peint_043_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_91.geometry}
          material={materials.papier_peint_054_Wall_Entity_Material}
          material-color={"brown"}
        />
        <mesh
          geometry={nodes.Object_92.geometry}
          material={materials.parquet_015_Room_Entity_Material}
          material-color={"green"}
        />
        <mesh
          geometry={nodes.Object_93.geometry}
          material={materials.parquet_022_Room_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_94.geometry}
          material={materials.piscine_001___piscine_001eau3sg}
          material-color={"green"}
        />
        <mesh
          geometry={nodes.Object_95.geometry}
          material={materials.plante_interieur_off___phong80}
          material-color={"green"}
        />
        <mesh
          geometry={nodes.Object_96.geometry}
          material={materials.plante_vase_off_001___phong37}
        />
        <mesh
          geometry={nodes.Object_97.geometry}
          material={materials.plante_vase_off_003___phong39}
        />
        <mesh
          geometry={nodes.Object_98.geometry}
          material={
            materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006glacon
          }
        />
        <mesh
          geometry={nodes.Object_99.geometry}
          material={
            materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006metal
          }
        />
        <mesh
          geometry={nodes.Object_100.geometry}
          material={
            materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006porte
          }
        />
        <mesh
          geometry={nodes.Object_101.geometry}
          material={materials.scan_tablebasse_001_blanc___bois_001}
        />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.scandinave_tex_005_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_103.geometry}
          material={materials.spa_octogonal___phong1sg}
        />
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.spa_octogonal___spa_octogonalspa_octogonal_jets}
        />
        <mesh
          geometry={nodes.Object_105.geometry}
          material={
            materials.tableau_vegetal___tableau_vegetaltableau_vegetal_feuille_lierre
          }
        />
        <mesh
          geometry={nodes.Object_106.geometry}
          material={
            materials.tableau_vegetal___tableau_vegetaltableau_vegetal_feuille_seule
          }
        />
        <mesh
          geometry={nodes.Object_107.geometry}
          material={
            materials.tableau_vegetal___tableau_vegetaltableau_vegetal_plante
          }
        />
        <mesh
          geometry={nodes.Object_108.geometry}
          material={materials.tabouret_off_003___phong300}
        />
        <mesh
          geometry={nodes.Object_109.geometry}
          material={materials.tex_bois_blanc}
        />
        <mesh
          geometry={nodes.Object_110.geometry}
          material={materials.tex_bois_marron_001}
        />
        <mesh
          geometry={nodes.Object_111.geometry}
          material={materials.tex_bois_scan_blanc_002}
        />
        <mesh
          geometry={nodes.Object_112.geometry}
          material={
            materials.tex_terrec_scan_turquoise_009_Wall_Entity_Material
          }
        />
        <mesh
          geometry={nodes.Object_113.geometry}
          material={materials.texture_scandinave_01_Wall_Entity_Material}
        />
        <mesh
          geometry={nodes.Object_114.geometry}
          material={materials.vase_fleur_off___phong94}
        />
      </group>
    </group>
  );
}
